$hypr = ~/.config/hypr
$hl = $hypr/hyprland
$cConf = ~/.config/caelestia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
env = GTK_IM_MODULE,fcitx
env = QT_IM_MODULE,fcitx
env = XMODIFIERS,@im=fcitx
env = WLR_RENDERER,opengl


# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

# Default monitor conf
# monitor=HDMI-A-1,1920x1080@60,auto,1
monitor=HDMI-A-1,preferred,auto,1
monitor=eDP-1,1920x1080@144,0x0,1

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher

# bind = $mainMod, Q, exec, $terminal
# bind = $mainMod, C, killactive,
# bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
# bind = $mainMod, E, exec, $fileManager
# bind = $mainMod, V, togglefloating,
# bind = $mainMod, R, exec, $menu
# User configs
exec = mkdir -p $cConf && touch -a $cConf/hypr-user.conf
source = $cConf/hypr-user.conf

exec-once = fcitx5

